/**
 * Centralised disclaimer for all LLM insight responses (bolt 023).
 * ADR-003: domain layer — pure functions, no side effects.
 */

export const INSIGHT_DISCLAIMER =
	"⚠️ This insight is generated by an AI model based on your portfolio data " +
	"as of the most recent recorded valuation. Rates and returns are assumed, " +
	"not guaranteed. Market conditions, tax rules, and personal circumstances " +
	"may differ significantly from modelled assumptions. This output is for " +
	"informational purposes only and does not constitute financial advice. " +
	"Consult a SEBI-registered investment advisor for personalised guidance.";

export function appendDisclaimer(narrative: string): string {
	if (!narrative.trim()) return INSIGHT_DISCLAIMER;
	return `${narrative}\n\n${INSIGHT_DISCLAIMER}`;
}
